name: Run tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'
          cache: 'npm'
      - name: Clean install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'
          cache: 'npm'
      - name: Clean install dependencies
        run: npm ci
      - name: Run Biome format check
        run: npm run format
